/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl;


import com.epita.assistants.ddl.tables.Move;
import com.epita.assistants.ddl.tables.Trainer;
import com.epita.assistants.ddl.tables.TrainerYakamon;
import com.epita.assistants.ddl.tables.Type;
import com.epita.assistants.ddl.tables.Yakadex;
import com.epita.assistants.ddl.tables.YakadexMoves;
import com.epita.assistants.ddl.tables.YakadexTypes;
import com.epita.assistants.ddl.tables.YakadexZones;
import com.epita.assistants.ddl.tables.Yakamon;
import com.epita.assistants.ddl.tables.YakamonZone;
import com.epita.assistants.ddl.tables.Zone;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>WEBSERVICE</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_24 = Indexes0.PRIMARY_KEY_24;
    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;
    public static final Index CONSTRAINT_INDEX_A = Indexes0.CONSTRAINT_INDEX_A;
    public static final Index CONSTRAINT_INDEX_AD = Indexes0.CONSTRAINT_INDEX_AD;
    public static final Index CONSTRAINT_INDEX_AD2 = Indexes0.CONSTRAINT_INDEX_AD2;
    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index CONSTRAINT_INDEX_D = Indexes0.CONSTRAINT_INDEX_D;
    public static final Index CONSTRAINT_INDEX_D7 = Indexes0.CONSTRAINT_INDEX_D7;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index CONSTRAINT_INDEX_B = Indexes0.CONSTRAINT_INDEX_B;
    public static final Index CONSTRAINT_INDEX_BC = Indexes0.CONSTRAINT_INDEX_BC;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index CONSTRAINT_INDEX_BD3 = Indexes0.CONSTRAINT_INDEX_BD3;
    public static final Index CONSTRAINT_INDEX_BD37 = Indexes0.CONSTRAINT_INDEX_BD37;
    public static final Index PRIMARY_KEY_BD3 = Indexes0.PRIMARY_KEY_BD3;
    public static final Index CONSTRAINT_INDEX_BD = Indexes0.CONSTRAINT_INDEX_BD;
    public static final Index CONSTRAINT_INDEX_BD8 = Indexes0.CONSTRAINT_INDEX_BD8;
    public static final Index PRIMARY_KEY_BD = Indexes0.PRIMARY_KEY_BD;
    public static final Index UC_YAKADEX_ZONES_INDEX_B = Indexes0.UC_YAKADEX_ZONES_INDEX_B;
    public static final Index CONSTRAINT_INDEX_D73 = Indexes0.CONSTRAINT_INDEX_D73;
    public static final Index PRIMARY_KEY_D7 = Indexes0.PRIMARY_KEY_D7;
    public static final Index CONSTRAINT_INDEX_C = Indexes0.CONSTRAINT_INDEX_C;
    public static final Index CONSTRAINT_INDEX_CD = Indexes0.CONSTRAINT_INDEX_CD;
    public static final Index CONSTRAINT_INDEX_CDF = Indexes0.CONSTRAINT_INDEX_CDF;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;
    public static final Index PRIMARY_KEY_2A = Indexes0.PRIMARY_KEY_2A;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_24 = Internal.createIndex("PRIMARY_KEY_24", Move.MOVE, new OrderField[] { Move.MOVE.NAME }, true);
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", Trainer.TRAINER, new OrderField[] { Trainer.TRAINER.UUID }, true);
        public static Index CONSTRAINT_INDEX_A = Internal.createIndex("CONSTRAINT_INDEX_A", TrainerYakamon.TRAINER_YAKAMON, new OrderField[] { TrainerYakamon.TRAINER_YAKAMON.YAKAMON_ID }, false);
        public static Index CONSTRAINT_INDEX_AD = Internal.createIndex("CONSTRAINT_INDEX_AD", TrainerYakamon.TRAINER_YAKAMON, new OrderField[] { TrainerYakamon.TRAINER_YAKAMON.TRAINER_ID }, false);
        public static Index CONSTRAINT_INDEX_AD2 = Internal.createIndex("CONSTRAINT_INDEX_AD2", TrainerYakamon.TRAINER_YAKAMON, new OrderField[] { TrainerYakamon.TRAINER_YAKAMON.YAKAMON_ID }, true);
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", TrainerYakamon.TRAINER_YAKAMON, new OrderField[] { TrainerYakamon.TRAINER_YAKAMON.ID }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Type.TYPE, new OrderField[] { Type.TYPE.NAME }, true);
        public static Index CONSTRAINT_INDEX_D = Internal.createIndex("CONSTRAINT_INDEX_D", Yakadex.YAKADEX, new OrderField[] { Yakadex.YAKADEX.PREVIOUS_EVOLUTION }, false);
        public static Index CONSTRAINT_INDEX_D7 = Internal.createIndex("CONSTRAINT_INDEX_D7", Yakadex.YAKADEX, new OrderField[] { Yakadex.YAKADEX.NEXT_EVOLUTION }, false);
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", Yakadex.YAKADEX, new OrderField[] { Yakadex.YAKADEX.NAME }, true);
        public static Index CONSTRAINT_INDEX_B = Internal.createIndex("CONSTRAINT_INDEX_B", YakadexMoves.YAKADEX_MOVES, new OrderField[] { YakadexMoves.YAKADEX_MOVES.YAKADEX_ID }, false);
        public static Index CONSTRAINT_INDEX_BC = Internal.createIndex("CONSTRAINT_INDEX_BC", YakadexMoves.YAKADEX_MOVES, new OrderField[] { YakadexMoves.YAKADEX_MOVES.MOVE_ID }, false);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", YakadexMoves.YAKADEX_MOVES, new OrderField[] { YakadexMoves.YAKADEX_MOVES.ID }, true);
        public static Index CONSTRAINT_INDEX_BD3 = Internal.createIndex("CONSTRAINT_INDEX_BD3", YakadexTypes.YAKADEX_TYPES, new OrderField[] { YakadexTypes.YAKADEX_TYPES.YAKADEX_ID }, false);
        public static Index CONSTRAINT_INDEX_BD37 = Internal.createIndex("CONSTRAINT_INDEX_BD37", YakadexTypes.YAKADEX_TYPES, new OrderField[] { YakadexTypes.YAKADEX_TYPES.TYPE_ID }, false);
        public static Index PRIMARY_KEY_BD3 = Internal.createIndex("PRIMARY_KEY_BD3", YakadexTypes.YAKADEX_TYPES, new OrderField[] { YakadexTypes.YAKADEX_TYPES.ID }, true);
        public static Index CONSTRAINT_INDEX_BD = Internal.createIndex("CONSTRAINT_INDEX_BD", YakadexZones.YAKADEX_ZONES, new OrderField[] { YakadexZones.YAKADEX_ZONES.YAKADEX_ID }, false);
        public static Index CONSTRAINT_INDEX_BD8 = Internal.createIndex("CONSTRAINT_INDEX_BD8", YakadexZones.YAKADEX_ZONES, new OrderField[] { YakadexZones.YAKADEX_ZONES.ZONE_ID }, false);
        public static Index PRIMARY_KEY_BD = Internal.createIndex("PRIMARY_KEY_BD", YakadexZones.YAKADEX_ZONES, new OrderField[] { YakadexZones.YAKADEX_ZONES.ID }, true);
        public static Index UC_YAKADEX_ZONES_INDEX_B = Internal.createIndex("UC_YAKADEX_ZONES_INDEX_B", YakadexZones.YAKADEX_ZONES, new OrderField[] { YakadexZones.YAKADEX_ZONES.YAKADEX_ID, YakadexZones.YAKADEX_ZONES.ZONE_ID }, true);
        public static Index CONSTRAINT_INDEX_D73 = Internal.createIndex("CONSTRAINT_INDEX_D73", Yakamon.YAKAMON, new OrderField[] { Yakamon.YAKAMON.YAKADEX_ID }, false);
        public static Index PRIMARY_KEY_D7 = Internal.createIndex("PRIMARY_KEY_D7", Yakamon.YAKAMON, new OrderField[] { Yakamon.YAKAMON.ID }, true);
        public static Index CONSTRAINT_INDEX_C = Internal.createIndex("CONSTRAINT_INDEX_C", YakamonZone.YAKAMON_ZONE, new OrderField[] { YakamonZone.YAKAMON_ZONE.YAKAMON_ID }, false);
        public static Index CONSTRAINT_INDEX_CD = Internal.createIndex("CONSTRAINT_INDEX_CD", YakamonZone.YAKAMON_ZONE, new OrderField[] { YakamonZone.YAKAMON_ZONE.ZONE_ID }, false);
        public static Index CONSTRAINT_INDEX_CDF = Internal.createIndex("CONSTRAINT_INDEX_CDF", YakamonZone.YAKAMON_ZONE, new OrderField[] { YakamonZone.YAKAMON_ZONE.YAKAMON_ID }, true);
        public static Index PRIMARY_KEY_C = Internal.createIndex("PRIMARY_KEY_C", YakamonZone.YAKAMON_ZONE, new OrderField[] { YakamonZone.YAKAMON_ZONE.ID }, true);
        public static Index PRIMARY_KEY_2A = Internal.createIndex("PRIMARY_KEY_2A", Zone.ZONE, new OrderField[] { Zone.ZONE.NAME }, true);
    }
}
