/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl;


import com.epita.assistants.ddl.tables.Move;
import com.epita.assistants.ddl.tables.Trainer;
import com.epita.assistants.ddl.tables.TrainerYakamon;
import com.epita.assistants.ddl.tables.Type;
import com.epita.assistants.ddl.tables.Yakadex;
import com.epita.assistants.ddl.tables.YakadexMoves;
import com.epita.assistants.ddl.tables.YakadexTypes;
import com.epita.assistants.ddl.tables.YakadexZones;
import com.epita.assistants.ddl.tables.Yakamon;
import com.epita.assistants.ddl.tables.YakamonZone;
import com.epita.assistants.ddl.tables.Zone;
import com.epita.assistants.ddl.tables.records.MoveRecord;
import com.epita.assistants.ddl.tables.records.TrainerRecord;
import com.epita.assistants.ddl.tables.records.TrainerYakamonRecord;
import com.epita.assistants.ddl.tables.records.TypeRecord;
import com.epita.assistants.ddl.tables.records.YakadexMovesRecord;
import com.epita.assistants.ddl.tables.records.YakadexRecord;
import com.epita.assistants.ddl.tables.records.YakadexTypesRecord;
import com.epita.assistants.ddl.tables.records.YakadexZonesRecord;
import com.epita.assistants.ddl.tables.records.YakamonRecord;
import com.epita.assistants.ddl.tables.records.YakamonZoneRecord;
import com.epita.assistants.ddl.tables.records.ZoneRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>WEBSERVICE</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TrainerYakamonRecord, Integer> IDENTITY_TRAINER_YAKAMON = Identities0.IDENTITY_TRAINER_YAKAMON;
    public static final Identity<YakamonZoneRecord, Integer> IDENTITY_YAKAMON_ZONE = Identities0.IDENTITY_YAKAMON_ZONE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MoveRecord> CONSTRAINT_24 = UniqueKeys0.CONSTRAINT_24;
    public static final UniqueKey<TrainerRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<TrainerYakamonRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<TrainerYakamonRecord> CONSTRAINT_AD20 = UniqueKeys0.CONSTRAINT_AD20;
    public static final UniqueKey<TypeRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<YakadexRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;
    public static final UniqueKey<YakadexMovesRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<YakadexTypesRecord> CONSTRAINT_BD3 = UniqueKeys0.CONSTRAINT_BD3;
    public static final UniqueKey<YakadexZonesRecord> CONSTRAINT_BD = UniqueKeys0.CONSTRAINT_BD;
    public static final UniqueKey<YakadexZonesRecord> UC_YAKADEX_ZONES = UniqueKeys0.UC_YAKADEX_ZONES;
    public static final UniqueKey<YakamonRecord> CONSTRAINT_D735 = UniqueKeys0.CONSTRAINT_D735;
    public static final UniqueKey<YakamonZoneRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<YakamonZoneRecord> CONSTRAINT_CDFD = UniqueKeys0.CONSTRAINT_CDFD;
    public static final UniqueKey<ZoneRecord> CONSTRAINT_2A = UniqueKeys0.CONSTRAINT_2A;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TrainerYakamonRecord, TrainerRecord> CONSTRAINT_AD2 = ForeignKeys0.CONSTRAINT_AD2;
    public static final ForeignKey<TrainerYakamonRecord, YakamonRecord> CONSTRAINT_AD = ForeignKeys0.CONSTRAINT_AD;
    public static final ForeignKey<YakadexRecord, YakadexRecord> CONSTRAINT_D7 = ForeignKeys0.CONSTRAINT_D7;
    public static final ForeignKey<YakadexRecord, YakadexRecord> CONSTRAINT_D73 = ForeignKeys0.CONSTRAINT_D73;
    public static final ForeignKey<YakadexMovesRecord, YakadexRecord> CONSTRAINT_BC = ForeignKeys0.CONSTRAINT_BC;
    public static final ForeignKey<YakadexMovesRecord, MoveRecord> CONSTRAINT_BCC = ForeignKeys0.CONSTRAINT_BCC;
    public static final ForeignKey<YakadexTypesRecord, YakadexRecord> CONSTRAINT_BD37 = ForeignKeys0.CONSTRAINT_BD37;
    public static final ForeignKey<YakadexTypesRecord, TypeRecord> CONSTRAINT_BD370 = ForeignKeys0.CONSTRAINT_BD370;
    public static final ForeignKey<YakadexZonesRecord, YakadexRecord> CONSTRAINT_BD8 = ForeignKeys0.CONSTRAINT_BD8;
    public static final ForeignKey<YakadexZonesRecord, ZoneRecord> CONSTRAINT_BD87 = ForeignKeys0.CONSTRAINT_BD87;
    public static final ForeignKey<YakamonRecord, YakadexRecord> CONSTRAINT_D7353 = ForeignKeys0.CONSTRAINT_D7353;
    public static final ForeignKey<YakamonZoneRecord, YakamonRecord> CONSTRAINT_CD = ForeignKeys0.CONSTRAINT_CD;
    public static final ForeignKey<YakamonZoneRecord, ZoneRecord> CONSTRAINT_CDF = ForeignKeys0.CONSTRAINT_CDF;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TrainerYakamonRecord, Integer> IDENTITY_TRAINER_YAKAMON = Internal.createIdentity(TrainerYakamon.TRAINER_YAKAMON, TrainerYakamon.TRAINER_YAKAMON.ID);
        public static Identity<YakamonZoneRecord, Integer> IDENTITY_YAKAMON_ZONE = Internal.createIdentity(YakamonZone.YAKAMON_ZONE, YakamonZone.YAKAMON_ZONE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MoveRecord> CONSTRAINT_24 = Internal.createUniqueKey(Move.MOVE, "CONSTRAINT_24", Move.MOVE.NAME);
        public static final UniqueKey<TrainerRecord> CONSTRAINT_E = Internal.createUniqueKey(Trainer.TRAINER, "CONSTRAINT_E", Trainer.TRAINER.UUID);
        public static final UniqueKey<TrainerYakamonRecord> CONSTRAINT_A = Internal.createUniqueKey(TrainerYakamon.TRAINER_YAKAMON, "CONSTRAINT_A", TrainerYakamon.TRAINER_YAKAMON.ID);
        public static final UniqueKey<TrainerYakamonRecord> CONSTRAINT_AD20 = Internal.createUniqueKey(TrainerYakamon.TRAINER_YAKAMON, "CONSTRAINT_AD20", TrainerYakamon.TRAINER_YAKAMON.YAKAMON_ID);
        public static final UniqueKey<TypeRecord> CONSTRAINT_2 = Internal.createUniqueKey(Type.TYPE, "CONSTRAINT_2", Type.TYPE.NAME);
        public static final UniqueKey<YakadexRecord> CONSTRAINT_D = Internal.createUniqueKey(Yakadex.YAKADEX, "CONSTRAINT_D", Yakadex.YAKADEX.NAME);
        public static final UniqueKey<YakadexMovesRecord> CONSTRAINT_B = Internal.createUniqueKey(YakadexMoves.YAKADEX_MOVES, "CONSTRAINT_B", YakadexMoves.YAKADEX_MOVES.ID);
        public static final UniqueKey<YakadexTypesRecord> CONSTRAINT_BD3 = Internal.createUniqueKey(YakadexTypes.YAKADEX_TYPES, "CONSTRAINT_BD3", YakadexTypes.YAKADEX_TYPES.ID);
        public static final UniqueKey<YakadexZonesRecord> CONSTRAINT_BD = Internal.createUniqueKey(YakadexZones.YAKADEX_ZONES, "CONSTRAINT_BD", YakadexZones.YAKADEX_ZONES.ID);
        public static final UniqueKey<YakadexZonesRecord> UC_YAKADEX_ZONES = Internal.createUniqueKey(YakadexZones.YAKADEX_ZONES, "UC_YAKADEX_ZONES", YakadexZones.YAKADEX_ZONES.YAKADEX_ID, YakadexZones.YAKADEX_ZONES.ZONE_ID);
        public static final UniqueKey<YakamonRecord> CONSTRAINT_D735 = Internal.createUniqueKey(Yakamon.YAKAMON, "CONSTRAINT_D735", Yakamon.YAKAMON.ID);
        public static final UniqueKey<YakamonZoneRecord> CONSTRAINT_C = Internal.createUniqueKey(YakamonZone.YAKAMON_ZONE, "CONSTRAINT_C", YakamonZone.YAKAMON_ZONE.ID);
        public static final UniqueKey<YakamonZoneRecord> CONSTRAINT_CDFD = Internal.createUniqueKey(YakamonZone.YAKAMON_ZONE, "CONSTRAINT_CDFD", YakamonZone.YAKAMON_ZONE.YAKAMON_ID);
        public static final UniqueKey<ZoneRecord> CONSTRAINT_2A = Internal.createUniqueKey(Zone.ZONE, "CONSTRAINT_2A", Zone.ZONE.NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TrainerYakamonRecord, TrainerRecord> CONSTRAINT_AD2 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_E, TrainerYakamon.TRAINER_YAKAMON, "CONSTRAINT_AD2", TrainerYakamon.TRAINER_YAKAMON.TRAINER_ID);
        public static final ForeignKey<TrainerYakamonRecord, YakamonRecord> CONSTRAINT_AD = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D735, TrainerYakamon.TRAINER_YAKAMON, "CONSTRAINT_AD", TrainerYakamon.TRAINER_YAKAMON.YAKAMON_ID);
        public static final ForeignKey<YakadexRecord, YakadexRecord> CONSTRAINT_D7 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, Yakadex.YAKADEX, "CONSTRAINT_D7", Yakadex.YAKADEX.PREVIOUS_EVOLUTION);
        public static final ForeignKey<YakadexRecord, YakadexRecord> CONSTRAINT_D73 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, Yakadex.YAKADEX, "CONSTRAINT_D73", Yakadex.YAKADEX.NEXT_EVOLUTION);
        public static final ForeignKey<YakadexMovesRecord, YakadexRecord> CONSTRAINT_BC = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, YakadexMoves.YAKADEX_MOVES, "CONSTRAINT_BC", YakadexMoves.YAKADEX_MOVES.YAKADEX_ID);
        public static final ForeignKey<YakadexMovesRecord, MoveRecord> CONSTRAINT_BCC = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_24, YakadexMoves.YAKADEX_MOVES, "CONSTRAINT_BCC", YakadexMoves.YAKADEX_MOVES.MOVE_ID);
        public static final ForeignKey<YakadexTypesRecord, YakadexRecord> CONSTRAINT_BD37 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, YakadexTypes.YAKADEX_TYPES, "CONSTRAINT_BD37", YakadexTypes.YAKADEX_TYPES.YAKADEX_ID);
        public static final ForeignKey<YakadexTypesRecord, TypeRecord> CONSTRAINT_BD370 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_2, YakadexTypes.YAKADEX_TYPES, "CONSTRAINT_BD370", YakadexTypes.YAKADEX_TYPES.TYPE_ID);
        public static final ForeignKey<YakadexZonesRecord, YakadexRecord> CONSTRAINT_BD8 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, YakadexZones.YAKADEX_ZONES, "CONSTRAINT_BD8", YakadexZones.YAKADEX_ZONES.YAKADEX_ID);
        public static final ForeignKey<YakadexZonesRecord, ZoneRecord> CONSTRAINT_BD87 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_2A, YakadexZones.YAKADEX_ZONES, "CONSTRAINT_BD87", YakadexZones.YAKADEX_ZONES.ZONE_ID);
        public static final ForeignKey<YakamonRecord, YakadexRecord> CONSTRAINT_D7353 = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D, Yakamon.YAKAMON, "CONSTRAINT_D7353", Yakamon.YAKAMON.YAKADEX_ID);
        public static final ForeignKey<YakamonZoneRecord, YakamonRecord> CONSTRAINT_CD = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_D735, YakamonZone.YAKAMON_ZONE, "CONSTRAINT_CD", YakamonZone.YAKAMON_ZONE.YAKAMON_ID);
        public static final ForeignKey<YakamonZoneRecord, ZoneRecord> CONSTRAINT_CDF = Internal.createForeignKey(com.epita.assistants.ddl.Keys.CONSTRAINT_2A, YakamonZone.YAKAMON_ZONE, "CONSTRAINT_CDF", YakamonZone.YAKAMON_ZONE.ZONE_ID);
    }
}
