/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl;


import com.epita.assistants.ddl.tables.Move;
import com.epita.assistants.ddl.tables.Trainer;
import com.epita.assistants.ddl.tables.TrainerYakamon;
import com.epita.assistants.ddl.tables.Type;
import com.epita.assistants.ddl.tables.Yakadex;
import com.epita.assistants.ddl.tables.YakadexMoves;
import com.epita.assistants.ddl.tables.YakadexTypes;
import com.epita.assistants.ddl.tables.YakadexZones;
import com.epita.assistants.ddl.tables.Yakamon;
import com.epita.assistants.ddl.tables.YakamonZone;
import com.epita.assistants.ddl.tables.Zone;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in WEBSERVICE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>WEBSERVICE.MOVE</code>.
     */
    public static final Move MOVE = Move.MOVE;

    /**
     * The table <code>WEBSERVICE.TRAINER</code>.
     */
    public static final Trainer TRAINER = Trainer.TRAINER;

    /**
     * The table <code>WEBSERVICE.TRAINER_YAKAMON</code>.
     */
    public static final TrainerYakamon TRAINER_YAKAMON = TrainerYakamon.TRAINER_YAKAMON;

    /**
     * The table <code>WEBSERVICE.TYPE</code>.
     */
    public static final Type TYPE = Type.TYPE;

    /**
     * The table <code>WEBSERVICE.YAKADEX</code>.
     */
    public static final Yakadex YAKADEX = Yakadex.YAKADEX;

    /**
     * The table <code>WEBSERVICE.YAKADEX_MOVES</code>.
     */
    public static final YakadexMoves YAKADEX_MOVES = YakadexMoves.YAKADEX_MOVES;

    /**
     * The table <code>WEBSERVICE.YAKADEX_TYPES</code>.
     */
    public static final YakadexTypes YAKADEX_TYPES = YakadexTypes.YAKADEX_TYPES;

    /**
     * The table <code>WEBSERVICE.YAKADEX_ZONES</code>.
     */
    public static final YakadexZones YAKADEX_ZONES = YakadexZones.YAKADEX_ZONES;

    /**
     * The table <code>WEBSERVICE.YAKAMON</code>.
     */
    public static final Yakamon YAKAMON = Yakamon.YAKAMON;

    /**
     * The table <code>WEBSERVICE.YAKAMON_ZONE</code>.
     */
    public static final YakamonZone YAKAMON_ZONE = YakamonZone.YAKAMON_ZONE;

    /**
     * The table <code>WEBSERVICE.ZONE</code>.
     */
    public static final Zone ZONE = Zone.ZONE;
}
