/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl;


import com.epita.assistants.ddl.tables.Move;
import com.epita.assistants.ddl.tables.Trainer;
import com.epita.assistants.ddl.tables.TrainerYakamon;
import com.epita.assistants.ddl.tables.Type;
import com.epita.assistants.ddl.tables.Yakadex;
import com.epita.assistants.ddl.tables.YakadexMoves;
import com.epita.assistants.ddl.tables.YakadexTypes;
import com.epita.assistants.ddl.tables.YakadexZones;
import com.epita.assistants.ddl.tables.Yakamon;
import com.epita.assistants.ddl.tables.YakamonZone;
import com.epita.assistants.ddl.tables.Zone;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webservice extends SchemaImpl {

    private static final long serialVersionUID = -2126958802;

    /**
     * The reference instance of <code>WEBSERVICE</code>
     */
    public static final Webservice WEBSERVICE = new Webservice();

    /**
     * The table <code>WEBSERVICE.MOVE</code>.
     */
    public final Move MOVE = com.epita.assistants.ddl.tables.Move.MOVE;

    /**
     * The table <code>WEBSERVICE.TRAINER</code>.
     */
    public final Trainer TRAINER = com.epita.assistants.ddl.tables.Trainer.TRAINER;

    /**
     * The table <code>WEBSERVICE.TRAINER_YAKAMON</code>.
     */
    public final TrainerYakamon TRAINER_YAKAMON = com.epita.assistants.ddl.tables.TrainerYakamon.TRAINER_YAKAMON;

    /**
     * The table <code>WEBSERVICE.TYPE</code>.
     */
    public final Type TYPE = com.epita.assistants.ddl.tables.Type.TYPE;

    /**
     * The table <code>WEBSERVICE.YAKADEX</code>.
     */
    public final Yakadex YAKADEX = com.epita.assistants.ddl.tables.Yakadex.YAKADEX;

    /**
     * The table <code>WEBSERVICE.YAKADEX_MOVES</code>.
     */
    public final YakadexMoves YAKADEX_MOVES = com.epita.assistants.ddl.tables.YakadexMoves.YAKADEX_MOVES;

    /**
     * The table <code>WEBSERVICE.YAKADEX_TYPES</code>.
     */
    public final YakadexTypes YAKADEX_TYPES = com.epita.assistants.ddl.tables.YakadexTypes.YAKADEX_TYPES;

    /**
     * The table <code>WEBSERVICE.YAKADEX_ZONES</code>.
     */
    public final YakadexZones YAKADEX_ZONES = com.epita.assistants.ddl.tables.YakadexZones.YAKADEX_ZONES;

    /**
     * The table <code>WEBSERVICE.YAKAMON</code>.
     */
    public final Yakamon YAKAMON = com.epita.assistants.ddl.tables.Yakamon.YAKAMON;

    /**
     * The table <code>WEBSERVICE.YAKAMON_ZONE</code>.
     */
    public final YakamonZone YAKAMON_ZONE = com.epita.assistants.ddl.tables.YakamonZone.YAKAMON_ZONE;

    /**
     * The table <code>WEBSERVICE.ZONE</code>.
     */
    public final Zone ZONE = com.epita.assistants.ddl.tables.Zone.ZONE;

    /**
     * No further instances allowed
     */
    private Webservice() {
        super("WEBSERVICE", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Move.MOVE,
            Trainer.TRAINER,
            TrainerYakamon.TRAINER_YAKAMON,
            Type.TYPE,
            Yakadex.YAKADEX,
            YakadexMoves.YAKADEX_MOVES,
            YakadexTypes.YAKADEX_TYPES,
            YakadexZones.YAKADEX_ZONES,
            Yakamon.YAKAMON,
            YakamonZone.YAKAMON_ZONE,
            Zone.ZONE);
    }
}
