/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables;


import com.epita.assistants.ddl.Indexes;
import com.epita.assistants.ddl.Keys;
import com.epita.assistants.ddl.Webservice;
import com.epita.assistants.ddl.tables.records.TypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Type extends TableImpl<TypeRecord> {

    private static final long serialVersionUID = 458031962;

    /**
     * The reference instance of <code>WEBSERVICE.TYPE</code>
     */
    public static final Type TYPE = new Type();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeRecord> getRecordType() {
        return TypeRecord.class;
    }

    /**
     * The column <code>WEBSERVICE.TYPE.NAME</code>.
     */
    public final TableField<TypeRecord, String> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>WEBSERVICE.TYPE</code> table reference
     */
    public Type() {
        this(DSL.name("TYPE"), null);
    }

    /**
     * Create an aliased <code>WEBSERVICE.TYPE</code> table reference
     */
    public Type(String alias) {
        this(DSL.name(alias), TYPE);
    }

    /**
     * Create an aliased <code>WEBSERVICE.TYPE</code> table reference
     */
    public Type(Name alias) {
        this(alias, TYPE);
    }

    private Type(Name alias, Table<TypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Type(Name alias, Table<TypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Type(Table<O> child, ForeignKey<O, TypeRecord> key) {
        super(child, key, TYPE);
    }

    @Override
    public Schema getSchema() {
        return Webservice.WEBSERVICE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_2);
    }

    @Override
    public UniqueKey<TypeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public List<UniqueKey<TypeRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeRecord>>asList(Keys.CONSTRAINT_2);
    }

    @Override
    public Type as(String alias) {
        return new Type(DSL.name(alias), this);
    }

    @Override
    public Type as(Name alias) {
        return new Type(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Type rename(String name) {
        return new Type(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Type rename(Name name) {
        return new Type(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
