/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables;


import com.epita.assistants.ddl.Indexes;
import com.epita.assistants.ddl.Keys;
import com.epita.assistants.ddl.Webservice;
import com.epita.assistants.ddl.tables.records.YakadexTypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YakadexTypes extends TableImpl<YakadexTypesRecord> {

    private static final long serialVersionUID = 51889875;

    /**
     * The reference instance of <code>WEBSERVICE.YAKADEX_TYPES</code>
     */
    public static final YakadexTypes YAKADEX_TYPES = new YakadexTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YakadexTypesRecord> getRecordType() {
        return YakadexTypesRecord.class;
    }

    /**
     * The column <code>WEBSERVICE.YAKADEX_TYPES.ID</code>.
     */
    public final TableField<YakadexTypesRecord, Integer> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WEBSERVICE.YAKADEX_TYPES.YAKADEX_ID</code>.
     */
    public final TableField<YakadexTypesRecord, String> YAKADEX_ID = createField(DSL.name("YAKADEX_ID"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>WEBSERVICE.YAKADEX_TYPES.TYPE_ID</code>.
     */
    public final TableField<YakadexTypesRecord, String> TYPE_ID = createField(DSL.name("TYPE_ID"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>WEBSERVICE.YAKADEX_TYPES</code> table reference
     */
    public YakadexTypes() {
        this(DSL.name("YAKADEX_TYPES"), null);
    }

    /**
     * Create an aliased <code>WEBSERVICE.YAKADEX_TYPES</code> table reference
     */
    public YakadexTypes(String alias) {
        this(DSL.name(alias), YAKADEX_TYPES);
    }

    /**
     * Create an aliased <code>WEBSERVICE.YAKADEX_TYPES</code> table reference
     */
    public YakadexTypes(Name alias) {
        this(alias, YAKADEX_TYPES);
    }

    private YakadexTypes(Name alias, Table<YakadexTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private YakadexTypes(Name alias, Table<YakadexTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> YakadexTypes(Table<O> child, ForeignKey<O, YakadexTypesRecord> key) {
        super(child, key, YAKADEX_TYPES);
    }

    @Override
    public Schema getSchema() {
        return Webservice.WEBSERVICE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_BD3, Indexes.CONSTRAINT_INDEX_BD37, Indexes.PRIMARY_KEY_BD3);
    }

    @Override
    public UniqueKey<YakadexTypesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_BD3;
    }

    @Override
    public List<UniqueKey<YakadexTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<YakadexTypesRecord>>asList(Keys.CONSTRAINT_BD3);
    }

    @Override
    public List<ForeignKey<YakadexTypesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<YakadexTypesRecord, ?>>asList(Keys.CONSTRAINT_BD37, Keys.CONSTRAINT_BD370);
    }

    public Yakadex yakadex() {
        return new Yakadex(this, Keys.CONSTRAINT_BD37);
    }

    public Type type() {
        return new Type(this, Keys.CONSTRAINT_BD370);
    }

    @Override
    public YakadexTypes as(String alias) {
        return new YakadexTypes(DSL.name(alias), this);
    }

    @Override
    public YakadexTypes as(Name alias) {
        return new YakadexTypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YakadexTypes rename(String name) {
        return new YakadexTypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YakadexTypes rename(Name name) {
        return new YakadexTypes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
