/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables;


import com.epita.assistants.ddl.Indexes;
import com.epita.assistants.ddl.Keys;
import com.epita.assistants.ddl.Webservice;
import com.epita.assistants.ddl.tables.records.YakamonRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yakamon extends TableImpl<YakamonRecord> {

    private static final long serialVersionUID = -1086818443;

    /**
     * The reference instance of <code>WEBSERVICE.YAKAMON</code>
     */
    public static final Yakamon YAKAMON = new Yakamon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YakamonRecord> getRecordType() {
        return YakamonRecord.class;
    }

    /**
     * The column <code>WEBSERVICE.YAKAMON.ID</code>.
     */
    public final TableField<YakamonRecord, UUID> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>WEBSERVICE.YAKAMON.NAME</code>.
     */
    public final TableField<YakamonRecord, String> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>WEBSERVICE.YAKAMON.YAKADEX_ID</code>.
     */
    public final TableField<YakamonRecord, String> YAKADEX_ID = createField(DSL.name("YAKADEX_ID"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>WEBSERVICE.YAKAMON</code> table reference
     */
    public Yakamon() {
        this(DSL.name("YAKAMON"), null);
    }

    /**
     * Create an aliased <code>WEBSERVICE.YAKAMON</code> table reference
     */
    public Yakamon(String alias) {
        this(DSL.name(alias), YAKAMON);
    }

    /**
     * Create an aliased <code>WEBSERVICE.YAKAMON</code> table reference
     */
    public Yakamon(Name alias) {
        this(alias, YAKAMON);
    }

    private Yakamon(Name alias, Table<YakamonRecord> aliased) {
        this(alias, aliased, null);
    }

    private Yakamon(Name alias, Table<YakamonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Yakamon(Table<O> child, ForeignKey<O, YakamonRecord> key) {
        super(child, key, YAKAMON);
    }

    @Override
    public Schema getSchema() {
        return Webservice.WEBSERVICE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_D73, Indexes.PRIMARY_KEY_D7);
    }

    @Override
    public UniqueKey<YakamonRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D735;
    }

    @Override
    public List<UniqueKey<YakamonRecord>> getKeys() {
        return Arrays.<UniqueKey<YakamonRecord>>asList(Keys.CONSTRAINT_D735);
    }

    @Override
    public List<ForeignKey<YakamonRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<YakamonRecord, ?>>asList(Keys.CONSTRAINT_D7353);
    }

    public Yakadex yakadex() {
        return new Yakadex(this, Keys.CONSTRAINT_D7353);
    }

    @Override
    public Yakamon as(String alias) {
        return new Yakamon(DSL.name(alias), this);
    }

    @Override
    public Yakamon as(Name alias) {
        return new Yakamon(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Yakamon rename(String name) {
        return new Yakamon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Yakamon rename(Name name) {
        return new Yakamon(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
