/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables.records;


import com.epita.assistants.ddl.tables.Yakamon;

import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YakamonRecord extends UpdatableRecordImpl<YakamonRecord> implements Record3<UUID, String, String> {

    private static final long serialVersionUID = 123950941;

    /**
     * Setter for <code>WEBSERVICE.YAKAMON.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKAMON.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKAMON.YAKADEX_ID</code>.
     */
    public void setYakadexId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON.YAKADEX_ID</code>.
     */
    public String getYakadexId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Yakamon.YAKAMON.ID;
    }

    @Override
    public Field<String> field2() {
        return Yakamon.YAKAMON.NAME;
    }

    @Override
    public Field<String> field3() {
        return Yakamon.YAKAMON.YAKADEX_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getYakadexId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getYakadexId();
    }

    @Override
    public YakamonRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public YakamonRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public YakamonRecord value3(String value) {
        setYakadexId(value);
        return this;
    }

    @Override
    public YakamonRecord values(UUID value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YakamonRecord
     */
    public YakamonRecord() {
        super(Yakamon.YAKAMON);
    }

    /**
     * Create a detached, initialised YakamonRecord
     */
    public YakamonRecord(UUID id, String name, String yakadexId) {
        super(Yakamon.YAKAMON);

        set(0, id);
        set(1, name);
        set(2, yakadexId);
    }
}
