/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables.records;


import com.epita.assistants.ddl.tables.YakamonZone;

import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YakamonZoneRecord extends UpdatableRecordImpl<YakamonZoneRecord> implements Record3<Integer, UUID, String> {

    private static final long serialVersionUID = 1263720182;

    /**
     * Setter for <code>WEBSERVICE.YAKAMON_ZONE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON_ZONE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKAMON_ZONE.YAKAMON_ID</code>.
     */
    public void setYakamonId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON_ZONE.YAKAMON_ID</code>.
     */
    public UUID getYakamonId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKAMON_ZONE.ZONE_ID</code>.
     */
    public void setZoneId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKAMON_ZONE.ZONE_ID</code>.
     */
    public String getZoneId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, UUID, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, UUID, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return YakamonZone.YAKAMON_ZONE.ID;
    }

    @Override
    public Field<UUID> field2() {
        return YakamonZone.YAKAMON_ZONE.YAKAMON_ID;
    }

    @Override
    public Field<String> field3() {
        return YakamonZone.YAKAMON_ZONE.ZONE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getYakamonId();
    }

    @Override
    public String component3() {
        return getZoneId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getYakamonId();
    }

    @Override
    public String value3() {
        return getZoneId();
    }

    @Override
    public YakamonZoneRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public YakamonZoneRecord value2(UUID value) {
        setYakamonId(value);
        return this;
    }

    @Override
    public YakamonZoneRecord value3(String value) {
        setZoneId(value);
        return this;
    }

    @Override
    public YakamonZoneRecord values(Integer value1, UUID value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YakamonZoneRecord
     */
    public YakamonZoneRecord() {
        super(YakamonZone.YAKAMON_ZONE);
    }

    /**
     * Create a detached, initialised YakamonZoneRecord
     */
    public YakamonZoneRecord(Integer id, UUID yakamonId, String zoneId) {
        super(YakamonZone.YAKAMON_ZONE);

        set(0, id);
        set(1, yakamonId);
        set(2, zoneId);
    }
}
