/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables.records;


import com.epita.assistants.ddl.tables.YakadexMoves;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YakadexMovesRecord extends UpdatableRecordImpl<YakadexMovesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1732837992;

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_MOVES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_MOVES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_MOVES.YAKADEX_ID</code>.
     */
    public void setYakadexId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_MOVES.YAKADEX_ID</code>.
     */
    public String getYakadexId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_MOVES.MOVE_ID</code>.
     */
    public void setMoveId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_MOVES.MOVE_ID</code>.
     */
    public String getMoveId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return YakadexMoves.YAKADEX_MOVES.ID;
    }

    @Override
    public Field<String> field2() {
        return YakadexMoves.YAKADEX_MOVES.YAKADEX_ID;
    }

    @Override
    public Field<String> field3() {
        return YakadexMoves.YAKADEX_MOVES.MOVE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getYakadexId();
    }

    @Override
    public String component3() {
        return getMoveId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getYakadexId();
    }

    @Override
    public String value3() {
        return getMoveId();
    }

    @Override
    public YakadexMovesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public YakadexMovesRecord value2(String value) {
        setYakadexId(value);
        return this;
    }

    @Override
    public YakadexMovesRecord value3(String value) {
        setMoveId(value);
        return this;
    }

    @Override
    public YakadexMovesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YakadexMovesRecord
     */
    public YakadexMovesRecord() {
        super(YakadexMoves.YAKADEX_MOVES);
    }

    /**
     * Create a detached, initialised YakadexMovesRecord
     */
    public YakadexMovesRecord(Integer id, String yakadexId, String moveId) {
        super(YakadexMoves.YAKADEX_MOVES);

        set(0, id);
        set(1, yakadexId);
        set(2, moveId);
    }
}
