/*
 * This file is generated by jOOQ.
 */
package com.epita.assistants.ddl.tables.records;


import com.epita.assistants.ddl.tables.YakadexTypes;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YakadexTypesRecord extends UpdatableRecordImpl<YakadexTypesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 901109287;

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_TYPES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_TYPES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_TYPES.YAKADEX_ID</code>.
     */
    public void setYakadexId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_TYPES.YAKADEX_ID</code>.
     */
    public String getYakadexId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>WEBSERVICE.YAKADEX_TYPES.TYPE_ID</code>.
     */
    public void setTypeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>WEBSERVICE.YAKADEX_TYPES.TYPE_ID</code>.
     */
    public String getTypeId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return YakadexTypes.YAKADEX_TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return YakadexTypes.YAKADEX_TYPES.YAKADEX_ID;
    }

    @Override
    public Field<String> field3() {
        return YakadexTypes.YAKADEX_TYPES.TYPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getYakadexId();
    }

    @Override
    public String component3() {
        return getTypeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getYakadexId();
    }

    @Override
    public String value3() {
        return getTypeId();
    }

    @Override
    public YakadexTypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public YakadexTypesRecord value2(String value) {
        setYakadexId(value);
        return this;
    }

    @Override
    public YakadexTypesRecord value3(String value) {
        setTypeId(value);
        return this;
    }

    @Override
    public YakadexTypesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YakadexTypesRecord
     */
    public YakadexTypesRecord() {
        super(YakadexTypes.YAKADEX_TYPES);
    }

    /**
     * Create a detached, initialised YakadexTypesRecord
     */
    public YakadexTypesRecord(Integer id, String yakadexId, String typeId) {
        super(YakadexTypes.YAKADEX_TYPES);

        set(0, id);
        set(1, yakadexId);
        set(2, typeId);
    }
}
